name: Scully Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cmgriffing/scully-gh-pages-action@v10
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: main
